- name: Install semgrep for static analysis
  ansible.builtin.command:
    cmd: pipx install semgrep
    creates: ~/.local/bin/semgrep
  register: semgrep_install
  retries: 3
  delay: 5
  until: semgrep_install is success

- name: Create symbolic link for semgrep in /usr/local/bin
  ansible.builtin.file:
    src: "{{ ansible_facts['user_dir'] }}/.local/bin/semgrep"
    dest: /usr/local/bin/semgrep
    state: link
  become: true
